---
# Practicalli Neovim
site_name: Practicalli Neovim
site_url: https://practical.li/neovim
site_description: Practical guide to Clojure development with Neovim
site_author: Practicalli
copyright: Copyright &copy 2023 Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/neovim/
edit_uri: https://github.com/practicalli/neovim/edit/main/docs/

# Deployment
# remote_name: practicalli/neovim
remote_branch: gh-pages

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes # Nav sections can have files
    - navigation.instant # Avoid page reloading for internal links
    - navigation.top
    - navigation.tracking # Update URL with sub-heading anchor names
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Override theme
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji ""
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized:
      # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [ MKDOCS_SOCIAL_CARDS_GENERATE, true ]

# Footer / Social Media
extra:
  analytics:
    provider: google
    property: G-P29SSN0GV6
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Introduction:
      - Overview: index.md
      - Community Projects: introduction/community-projects.md
      - REPL Workflow: introduction/repl-workflow.md
      - Features: introduction/features.md
      - Fennel: introduction/fennel.md
      - Contributing: introduction/contributing.md
      - Writing Tips: introduction/writing-tips.md
  - Install:
      - Overview: install/index.md
      - Clojure: install/clojure.md
      - Neovim: install/neovim.md
  - Neovim configuration:
      - configuration/index.md
      - AstroNvim:
          - configuration/astronvim/index.md
          - Config Design: configuration/astronvim/config-design.md
      - Practicalli:
          - configuration/practicalli/index.md
          - Config Design: configuration/practicalli/config-design.md
          - Packer: configuration/practicalli/packer.md
          - Packages:
              - configuration/practicalli/packages/index.md
              - Status Line: configuration/practicalli/packages/lualine.md
              - Treesitter: configuration/practicalli/packages/nvim-treesitter.md
  - Neovim Basics:
      - neovim-basics/index.md
      - File Buffer Window: neovim-basics/files-buffers-windows.md
      - Multi-modal Editing: neovim-basics/multi-modal-editing.md
      - Search Replace: neovim-basics/search-replace.md
      - Comments: neovim-basics/comments.md
      - Snippets: neovim-basics/snippets.md
      - Package Manager: neovim-basics/plugin-manager.md
      - Multiple Cursors: neovim-basics/multiple-cursors.md
      - Zen Mode: neovim-basics/zen-mode.md
      - Terminal: neovim-basics/terminal.md
  - Clojure REPL Workflow:
      - repl-driven-development/index.md
      - Conjure: repl-driven-development/conjure.md
      - LSP: repl-driven-development/language-server-protocol.md
      - Testing: repl-driven-development/testing.md
  - Version Control:
      - version-control/index.md
      - Lazygit: version-control/lazygit.md
      - Neogit: version-control/neogit.md
      - Octo: version-control/octo.md
      - Open In GitHub: version-control/open-in-github.md
  - API tools:
      - api-tools/index.md
  - Ultra-Mobile Neovim:
      - termux/index.md
      - F-Droid: termux/fdroid-install.md
      - Termux Setup: termux/setup.md
      - Using Termux: termux/using-termux.md
      - Git: termux/git.md
      - Zsh: termux/custom-shell.md
      - Clojure: termux/clojure-development.md
      - Neovim: termux/neovim.md
  - Reference:
      - Vim Style Editing:
          - reference/vim-style/index.md
          - reference/vim-style/case.md
          - reference/vim-style/g-menu.md
          - reference/vim-style/key-binding-reference.md
          - reference/vim-style/moving-around.md
          - reference/vim-style/motions.md
          - reference/vim-style/narrowing.md
          - reference/vim-style/speaking-vim.md
          - reference/vim-style/vim-quick-reference.md
          - reference/vim-style/vim-tips-for-developers.md
          - reference/vim-style/visual-select.md
          - reference/vim-style/z-menu.md
      - reference/aligning-text.md
      - Neovim:
          - reference/neovim/index.md
          - reference/neovim/standard-path.md
          - Language Providers: reference/neovim/language-providers.md
          - Standard Path: reference/neovim/standard-path.md
      - Lua Language:
          - reference/lua-language/index.md
